# docker-compose.yml
version: '3.8'
services:
  postgres:
    image: postgres:15 # 你可以选择你需要的 postgres 版本
    container_name: steam-postgres-dev
    restart: always
    environment:
      POSTGRES_USER: user_dev      # 设置你的开发用户名
      POSTGRES_PASSWORD: password_dev # 设置你的开发密码
      POSTGRES_DB: steam_dev       # 设置你的开发数据库名
    ports:
      - "5432:5432" # 将本机的 5432 端口映射到容器的 5432 端口
    volumes:
      - postgres_data:/var/lib/postgresql/data # 将数据持久化，防止容器重启后数据丢失

volumes:
  postgres_data: